# Generated by Django 4.1.7 on 2023-05-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_posts_user_alter_posts_signupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
