# Generated by Django 4.1.7 on 2023-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
