# Generated by Django 4.1.7 on 2023-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_uploadimage_image_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
