# Generated by Django 4.1.7 on 2023-05-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
