# Generated by Django 4.1.7 on 2023-05-31 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_addpost_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='addpost',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='addpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
